### ISSUE TITLE
能否将关闭、打开、登录自动化

### ISSUE THREAD

**Issue by cedricporter** [Raytone-D/puppet#1]
项目很赞，纯 Python 调 Win API 就搞定了。请问后续是否有计划自动化关闭、打开、登录等流程？

**Comment by Raytone-D** [comment]
如果是用同花顺官版的，应该不需要等太久就能实现自动登录。目前还在做和交互部分。

**Comment by Raytone-D** [comment]
重点是，交易开户端的自动关闭、打开、登录，都不是交易的一部分。目前还没精力放到这个地方去。
