### ISSUE TITLE
将cancel 方法重命名为cancel_order，并重写业务逻辑。

### ISSUE THREAD

**Issue by Raytone-D** [Raytone-D/puppet#12]

**Comment by pchaos** [comment]
def cancel(self, symbol=None, choice='buy'):
函数内有语法错误。
目前改为：
        # print("请尽快将"buy"改成"cancel_buy", "sell"改成"cancel_sell"，并移植到cancel_order方法。")
        time.sleep(3)
        cases = {'buy': 'cancel_buy', 'sell': 'cancel_sell'}
        self.cancel_order(cases.get(choice))

**Comment by Raytone-D** [comment]
多谢反馈，已经删除该函数。
